# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xcon_imperial_baking.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_XCon_Imperial_Baking(object):
    def setupUi(self, XCon_Imperial_Baking):
        XCon_Imperial_Baking.setObjectName("XCon_Imperial_Baking")
        XCon_Imperial_Baking.resize(1272, 761)
        self.centralWidget = QtWidgets.QWidget(XCon_Imperial_Baking)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.pushButton_import = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_import.setObjectName("pushButton_import")
        self.gridLayout_2.addWidget(self.pushButton_import, 1, 8, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 7, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 6, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 5, 1, 1)
        self.lineEdit_data = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_data.setObjectName("lineEdit_data")
        self.gridLayout_2.addWidget(self.lineEdit_data, 1, 1, 1, 5)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 8, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 4, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 3, 1, 1)
        self.pushButton_browse = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.gridLayout_2.addWidget(self.pushButton_browse, 1, 0, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_monitoring = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_monitoring.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.radioButton_monitoring.setAutoFillBackground(False)
        self.radioButton_monitoring.setObjectName("radioButton_monitoring")
        self.gridLayout_5.addWidget(self.radioButton_monitoring, 0, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_5, 1, 6, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 4)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 2, 0, 1, 1)
        self.verticalLayout_pressure = QtWidgets.QVBoxLayout()
        self.verticalLayout_pressure.setSpacing(6)
        self.verticalLayout_pressure.setObjectName("verticalLayout_pressure")
        self.gridLayout.addLayout(self.verticalLayout_pressure, 7, 1, 2, 3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_ch_3 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_3.setObjectName("lineEdit_ch_3")
        self.gridLayout_4.addWidget(self.lineEdit_ch_3, 8, 1, 1, 1)
        self.radioButton_ch_8 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_8.setAutoExclusive(False)
        self.radioButton_ch_8.setObjectName("radioButton_ch_8")
        self.gridLayout_4.addWidget(self.radioButton_ch_8, 13, 0, 1, 1)
        self.lineEdit_ch_4 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_4.setObjectName("lineEdit_ch_4")
        self.gridLayout_4.addWidget(self.lineEdit_ch_4, 9, 1, 1, 1)
        self.radioButton_ch_4 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_4.setAutoExclusive(False)
        self.radioButton_ch_4.setObjectName("radioButton_ch_4")
        self.gridLayout_4.addWidget(self.radioButton_ch_4, 9, 0, 1, 1)
        self.lineEdit_ch_7 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_7.setObjectName("lineEdit_ch_7")
        self.gridLayout_4.addWidget(self.lineEdit_ch_7, 12, 1, 1, 1)
        self.radioButton_ch_7 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_7.setAutoExclusive(False)
        self.radioButton_ch_7.setObjectName("radioButton_ch_7")
        self.gridLayout_4.addWidget(self.radioButton_ch_7, 12, 0, 1, 1)
        self.radioButton_ch_2 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_2.setAutoExclusive(False)
        self.radioButton_ch_2.setObjectName("radioButton_ch_2")
        self.gridLayout_4.addWidget(self.radioButton_ch_2, 7, 0, 1, 1)
        self.radioButton_ch_3 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_3.setAutoExclusive(False)
        self.radioButton_ch_3.setObjectName("radioButton_ch_3")
        self.gridLayout_4.addWidget(self.radioButton_ch_3, 8, 0, 1, 1)
        self.lineEdit_ch_1 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_1.setObjectName("lineEdit_ch_1")
        self.gridLayout_4.addWidget(self.lineEdit_ch_1, 2, 1, 1, 1)
        self.lineEdit_ch_8 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_8.setObjectName("lineEdit_ch_8")
        self.gridLayout_4.addWidget(self.lineEdit_ch_8, 13, 1, 1, 1)
        self.radioButton_ch_6 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_6.setAutoExclusive(False)
        self.radioButton_ch_6.setObjectName("radioButton_ch_6")
        self.gridLayout_4.addWidget(self.radioButton_ch_6, 11, 0, 1, 1)
        self.radioButton_ch_1 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_1.setAutoExclusive(False)
        self.radioButton_ch_1.setObjectName("radioButton_ch_1")
        self.gridLayout_4.addWidget(self.radioButton_ch_1, 2, 0, 1, 1)
        self.lineEdit_ch_2 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_2.setObjectName("lineEdit_ch_2")
        self.gridLayout_4.addWidget(self.lineEdit_ch_2, 7, 1, 1, 1)
        self.radioButton_ch_5 = QtWidgets.QRadioButton(self.centralWidget)
        self.radioButton_ch_5.setAutoExclusive(False)
        self.radioButton_ch_5.setObjectName("radioButton_ch_5")
        self.gridLayout_4.addWidget(self.radioButton_ch_5, 10, 0, 1, 1)
        self.lineEdit_ch_6 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_6.setObjectName("lineEdit_ch_6")
        self.gridLayout_4.addWidget(self.lineEdit_ch_6, 11, 1, 1, 1)
        self.lineEdit_ch_5 = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit_ch_5.setObjectName("lineEdit_ch_5")
        self.gridLayout_4.addWidget(self.lineEdit_ch_5, 10, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 4, 2, 1)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem10, 8, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 0, 4, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 3, 0, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem13, 4, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 0, 2, 1, 1)
        self.verticalLayout_temp = QtWidgets.QVBoxLayout()
        self.verticalLayout_temp.setSpacing(6)
        self.verticalLayout_temp.setObjectName("verticalLayout_temp")
        self.gridLayout.addLayout(self.verticalLayout_temp, 3, 1, 2, 3)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 0, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem16, 0, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem17, 0, 4, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem18, 0, 7, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem19, 0, 1, 1, 1)
        self.pushButton_Start = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.gridLayout_3.addWidget(self.pushButton_Start, 1, 6, 1, 1)
        self.pushButton_Stop = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.gridLayout_3.addWidget(self.pushButton_Stop, 1, 7, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem20, 0, 3, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem21, 0, 0, 1, 1)
        self.pushButton_Browse1 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Browse1.setObjectName("pushButton_Browse1")
        self.gridLayout_3.addWidget(self.pushButton_Browse1, 1, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem22, 0, 2, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem23, 0, 6, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem24, 0, 5, 1, 1)
        self.lineEdit_savefile = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_savefile.setObjectName("lineEdit_savefile")
        self.gridLayout_3.addWidget(self.lineEdit_savefile, 1, 1, 1, 5)
        self.lineEdit_ch1in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch1in.setObjectName("lineEdit_ch1in")
        self.gridLayout_3.addWidget(self.lineEdit_ch1in, 2, 0, 1, 1)
        self.lineEdit_ch2in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch2in.setObjectName("lineEdit_ch2in")
        self.gridLayout_3.addWidget(self.lineEdit_ch2in, 2, 1, 1, 1)
        self.lineEdit_ch3in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch3in.setObjectName("lineEdit_ch3in")
        self.gridLayout_3.addWidget(self.lineEdit_ch3in, 2, 2, 1, 1)
        self.lineEdit_ch4in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch4in.setObjectName("lineEdit_ch4in")
        self.gridLayout_3.addWidget(self.lineEdit_ch4in, 2, 3, 1, 1)
        self.lineEdit_ch5in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch5in.setObjectName("lineEdit_ch5in")
        self.gridLayout_3.addWidget(self.lineEdit_ch5in, 2, 4, 1, 1)
        self.lineEdit_ch6in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch6in.setObjectName("lineEdit_ch6in")
        self.gridLayout_3.addWidget(self.lineEdit_ch6in, 2, 5, 1, 1)
        self.lineEdit_ch7in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch7in.setObjectName("lineEdit_ch7in")
        self.gridLayout_3.addWidget(self.lineEdit_ch7in, 2, 6, 1, 1)
        self.lineEdit_ch8in = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ch8in.setObjectName("lineEdit_ch8in")
        self.gridLayout_3.addWidget(self.lineEdit_ch8in, 2, 7, 1, 1)
        self.label_ch1 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch1.setObjectName("label_ch1")
        self.gridLayout_3.addWidget(self.label_ch1, 3, 0, 1, 1)
        self.label_ch2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch2.setObjectName("label_ch2")
        self.gridLayout_3.addWidget(self.label_ch2, 3, 1, 1, 1)
        self.label_ch3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch3.setObjectName("label_ch3")
        self.gridLayout_3.addWidget(self.label_ch3, 3, 2, 1, 1)
        self.label_ch4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch4.setObjectName("label_ch4")
        self.gridLayout_3.addWidget(self.label_ch4, 3, 3, 1, 1)
        self.label_ch5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch5.setObjectName("label_ch5")
        self.gridLayout_3.addWidget(self.label_ch5, 3, 4, 1, 1)
        self.label_ch6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch6.setObjectName("label_ch6")
        self.gridLayout_3.addWidget(self.label_ch6, 3, 5, 1, 1)
        self.label_ch7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch7.setObjectName("label_ch7")
        self.gridLayout_3.addWidget(self.label_ch7, 3, 6, 1, 1)
        self.label_ch8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_ch8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch8.setObjectName("label_ch8")
        self.gridLayout_3.addWidget(self.label_ch8, 3, 7, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 4)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem25, 1, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem26, 7, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        XCon_Imperial_Baking.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(XCon_Imperial_Baking)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1272, 21))
        self.menuBar.setObjectName("menuBar")
        XCon_Imperial_Baking.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(XCon_Imperial_Baking)
        self.mainToolBar.setObjectName("mainToolBar")
        XCon_Imperial_Baking.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(XCon_Imperial_Baking)
        self.statusBar.setObjectName("statusBar")
        XCon_Imperial_Baking.setStatusBar(self.statusBar)

        self.retranslateUi(XCon_Imperial_Baking)
        QtCore.QMetaObject.connectSlotsByName(XCon_Imperial_Baking)

    def retranslateUi(self, XCon_Imperial_Baking):
        _translate = QtCore.QCoreApplication.translate
        XCon_Imperial_Baking.setWindowTitle(_translate("XCon_Imperial_Baking", "XCon_Imperial_Baking"))
        self.groupBox.setTitle(_translate("XCon_Imperial_Baking", "GroupBox"))
        self.pushButton_import.setText(_translate("XCon_Imperial_Baking", "go"))
        self.pushButton_browse.setText(_translate("XCon_Imperial_Baking", "Browse"))
        self.radioButton_monitoring.setText(_translate("XCon_Imperial_Baking", "Monitoring"))
        self.radioButton_ch_8.setText(_translate("XCon_Imperial_Baking", "Channel 8"))
        self.radioButton_ch_4.setText(_translate("XCon_Imperial_Baking", "Channel 4"))
        self.radioButton_ch_7.setText(_translate("XCon_Imperial_Baking", "Channel 7"))
        self.radioButton_ch_2.setText(_translate("XCon_Imperial_Baking", "Channel 2"))
        self.radioButton_ch_3.setText(_translate("XCon_Imperial_Baking", "Channel 3"))
        self.radioButton_ch_6.setText(_translate("XCon_Imperial_Baking", "Channel 6"))
        self.radioButton_ch_1.setText(_translate("XCon_Imperial_Baking", "Channel 1"))
        self.radioButton_ch_5.setText(_translate("XCon_Imperial_Baking", "Channel 5"))
        self.groupBox_2.setTitle(_translate("XCon_Imperial_Baking", "GroupBox"))
        self.pushButton_Start.setText(_translate("XCon_Imperial_Baking", "Start"))
        self.pushButton_Stop.setText(_translate("XCon_Imperial_Baking", "Stop"))
        self.pushButton_Browse1.setText(_translate("XCon_Imperial_Baking", "Browse"))
        self.label_ch1.setText(_translate("XCon_Imperial_Baking", "Channel 1"))
        self.label_ch2.setText(_translate("XCon_Imperial_Baking", "Channel 2"))
        self.label_ch3.setText(_translate("XCon_Imperial_Baking", "Channel 3"))
        self.label_ch4.setText(_translate("XCon_Imperial_Baking", "Channel 4"))
        self.label_ch5.setText(_translate("XCon_Imperial_Baking", "Channel 5"))
        self.label_ch6.setText(_translate("XCon_Imperial_Baking", "Channel 6"))
        self.label_ch7.setText(_translate("XCon_Imperial_Baking", "Channel 7"))
        self.label_ch8.setText(_translate("XCon_Imperial_Baking", "Channel 8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    XCon_Imperial_Baking = QtWidgets.QMainWindow()
    ui = Ui_XCon_Imperial_Baking()
    ui.setupUi(XCon_Imperial_Baking)
    XCon_Imperial_Baking.show()
    sys.exit(app.exec_())

